- name: Remove asset
  uses: flcdrg/remove-release-asset-action@v1
  id: remove
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
      release_id: ${{ steps.create-test-release.outputs.id }}
      asset_name: package.json
